/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_uurobot_serialportcompiler_NativeUtils */

#ifndef _Included_com_uurobot_serialportcompiler_NativeUtils
#define _Included_com_uurobot_serialportcompiler_NativeUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_uurobot_serialportcompiler_NativeUtils
 * Method:    open
 * Signature: (Ljava/lang/String;II)Ljava/io/FileDescriptor;
 */
JNIEXPORT jobject JNICALL Java_com_uurobot_serialportcompiler_NativeUtils_open
  (JNIEnv *, jobject, jstring, jint, jint);

/*
 * Class:     com_uurobot_serialportcompiler_NativeUtils
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_uurobot_serialportcompiler_NativeUtils_close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
