/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_uurobot_serialportcompiler_jniTest_SerialPortMgr */

#ifndef _Included_com_uurobot_serialportcompiler_jniTest_SerialPortMgr
#define _Included_com_uurobot_serialportcompiler_jniTest_SerialPortMgr
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_uurobot_serialportcompiler_jniTest_SerialPortMgr
 * Method:    open
 * Signature: (Ljava/lang/String;II)Z
 */
JNIEXPORT jboolean JNICALL Java_com_uurobot_serialportcompiler_jniTest_SerialPortMgr_open
  (JNIEnv *, jclass, jstring, jint, jint);

/*
 * Class:     com_uurobot_serialportcompiler_jniTest_SerialPortMgr
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_uurobot_serialportcompiler_jniTest_SerialPortMgr_close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
