/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_uurobot_serialportcompiler_jniSerialport_TtyNativeControl */

#ifndef _Included_com_uurobot_serialportcompiler_jniSerialport_TtyNativeControl
#define _Included_com_uurobot_serialportcompiler_jniSerialport_TtyNativeControl
#ifdef __cplusplus
extern "C" {
#endif
#undef com_uurobot_serialportcompiler_jniSerialport_TtyNativeControl_TTY_MSG_RECEIVE
#define com_uurobot_serialportcompiler_jniSerialport_TtyNativeControl_TTY_MSG_RECEIVE 1L
#undef com_uurobot_serialportcompiler_jniSerialport_TtyNativeControl_TTY_CLOSE_DEVICE
#define com_uurobot_serialportcompiler_jniSerialport_TtyNativeControl_TTY_CLOSE_DEVICE 2L
/*
 * Class:     com_uurobot_serialportcompiler_jniSerialport_TtyNativeControl
 * Method:    native_setup
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_uurobot_serialportcompiler_jniSerialport_TtyNativeControl_native_1setup
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_uurobot_serialportcompiler_jniSerialport_TtyNativeControl
 * Method:    _openTty
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_uurobot_serialportcompiler_jniSerialport_TtyNativeControl__1openTty
  (JNIEnv *, jobject);

/*
 * Class:     com_uurobot_serialportcompiler_jniSerialport_TtyNativeControl
 * Method:    _closeTty
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_uurobot_serialportcompiler_jniSerialport_TtyNativeControl__1closeTty
  (JNIEnv *, jobject);

/*
 * Class:     com_uurobot_serialportcompiler_jniSerialport_TtyNativeControl
 * Method:    _sendMsgToTty
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_com_uurobot_serialportcompiler_jniSerialport_TtyNativeControl__1sendMsgToTty
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_uurobot_serialportcompiler_jniSerialport_TtyNativeControl
 * Method:    _receiveMsgFromTty
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_uurobot_serialportcompiler_jniSerialport_TtyNativeControl__1receiveMsgFromTty
  (JNIEnv *, jobject);

/*
 * Class:     com_uurobot_serialportcompiler_jniSerialport_TtyNativeControl
 * Method:    _configTty
 * Signature: (ICII)I
 */
JNIEXPORT jint JNICALL Java_com_uurobot_serialportcompiler_jniSerialport_TtyNativeControl__1configTty
  (JNIEnv *, jobject, jint, jchar, jint, jint);

/*
 * Class:     com_uurobot_serialportcompiler_jniSerialport_TtyNativeControl
 * Method:    _setMode
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_uurobot_serialportcompiler_jniSerialport_TtyNativeControl__1setMode
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
